config/routes.rb
Rails.application.routes.draw do
  resources :swims
  devise_for :users

  root to:'swims#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/swim.rb
class Swim < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :swims
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/swims_controller.rb
class SwimsController < ApplicationController
  before_action :set_swim, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /swims
  # GET /swims.json
  def index
    @swims = Swim.all
  end

  # GET /swims/1
  # GET /swims/1.json
  def show
  end

  # GET /swims/new
  def new
    @swim = Swim.new
  end

  # GET /swims/1/edit
  def edit
  end

  # POST /swims
  # POST /swims.json
  def create
    @swim = Swim.new(swim_params)

    respond_to do |format|
      if @swim.save
        format.html { redirect_to @swim, notice: 'Swim was successfully created.' }
        format.json { render :show, status: :created, location: @swim }
      else
        format.html { render :new }
        format.json { render json: @swim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /swims/1
  # PATCH/PUT /swims/1.json
  def update
    respond_to do |format|
      if @swim.update(swim_params)
        format.html { redirect_to @swim, notice: 'Swim was successfully updated.' }
        format.json { render :show, status: :ok, location: @swim }
      else
        format.html { render :edit }
        format.json { render json: @swim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /swims/1
  # DELETE /swims/1.json
  def destroy
    @swim.destroy
    respond_to do |format|
      format.html { redirect_to swims_url, notice: 'Swim was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_swim
      @swim = Swim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def swim_params
      params.require(:swim).permit(:user_id, :distance, :swim_date, :lengths, :duration_minutes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/swims_helper.rb
module SwimsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <% if @page_title %>
      <title>Swimtrack | <%= "#{@page_title}" %></title>
    <% else %>
      <title><%= content_for?(:title) ? yield(:title) : "Swimtrack" %></title>
    <% end %>
    <%= csrf_meta_tags %>
      <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <!--[if IE]><script type="text/javascript" src="excanvas.js"></script><![endif]-->

    <script type="text/javascript">
      //disappear flash messages after X seconds
      window.setTimeout(function() {
        $(".alert-success").fadeTo(500, 0).slideUp(500, function(){
          $(this).remove();
        });
        $(".alert-danger").fadeTo(500, 0).slideUp(500, function(){
          $(this).remove();
        });
      }, 3000);



      function addAlert(message) {
        $('#alerts').append('<div class="alert alert-success">' +
          '<button type="button" class="close" data-dismiss="alert">' +
          '&times;</button>' + message + '</div>');
      }
    </script>
  </head>
  <body>
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><i class="fa fa-bullhorn fa-lg"></i>  Swimtrack</a>
        <% if @form_title %>
          <span class="navbar-brand"><b><%= @form_title %></b></span>
        <% end %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav nav-pills pull-right">
          <% if user_signed_in? %>
            <!-- menu items for signed in user here -->
          <% end %>
					<%= render 'devise/menu/registration_items' %>
					<%= render 'devise/menu/login_items' %>
          </ul>
        </div>
      </div>
    </div>
    <div class="container">

      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <div id="alerts"></div>
          <%= yield %>
        </div>
        <% if !user_signed_in? && request.fullpath != '/users/sign_up' && request.fullpath != '/users' %>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <%= render 'devise/sessions/new' %>
          </div>
        </div>
        <% end %>
      </div><!--/row-->

      <footer>
				<br/><br/><br/>
        <!-- <p>&copy; Matt Thomas 2014</p>-->
      </footer>

    </div> <!-- /container -->
    <br/><br/>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/swims/_form.html.erb
<%= form_for @swim, :html => { :class => "form-horizontal swim" } do |f| %>

  <% if @swim.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@swim.errors.count, "error") %> prohibited this swim from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @swim.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:user_id) %>
  </div>
  <div class="form-group">
    <%= f.label :distance, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :distance, :class => 'form-control' %>
    </div>
    <%=f.error_span(:distance) %>
  </div>
  <div class="form-group">
    <%= f.label :swim_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :swim_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:swim_date) %>
  </div>
  <div class="form-group">
    <%= f.label :lengths, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lengths, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lengths) %>
  </div>
  <div class="form-group">
    <%= f.label :duration_minutes, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :duration_minutes, :class => 'form-control' %>
    </div>
    <%=f.error_span(:duration_minutes) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                swims_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/swims/edit.html.erb
<%- model_class = Swim -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/swims/index.html.erb
<%- model_class = Swim -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:distance) %></th>
      <th><%= model_class.human_attribute_name(:swim_date) %></th>
      <th><%= model_class.human_attribute_name(:lengths) %></th>
      <th><%= model_class.human_attribute_name(:duration_minutes) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @swims.each do |swim| %>
      <tr>
        <td><%= link_to swim.id, swim_path(swim) %></td>
        <td><%= swim.user_id %></td>
        <td><%= swim.distance %></td>
        <td><%= swim.swim_date %></td>
        <td><%= swim.lengths %></td>
        <td><%= swim.duration_minutes %></td>
        <td><%=l swim.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_swim_path(swim), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      swim_path(swim),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_swim_path,
            :class => 'btn btn-primary' %>

app/views/swims/new.html.erb
<%- model_class = Swim -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/swims/show.html.erb
<%- model_class = Swim -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @swim.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:distance) %>:</strong></dt>
  <dd><%= @swim.distance %></dd>
  <dt><strong><%= model_class.human_attribute_name(:swim_date) %>:</strong></dt>
  <dd><%= @swim.swim_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lengths) %>:</strong></dt>
  <dd><%= @swim.lengths %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duration_minutes) %>:</strong></dt>
  <dd><%= @swim.duration_minutes %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              swims_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_swim_path(@swim), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              swim_path(@swim),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>